CREATE OR REPLACE PACKAGE WRK_INSERT_PKG AS 
PROCEDURE WRK_INSERT (EXT_TABLE_NAME IN VARCHAR2, WRK_TABLE_NAME IN VARCHAR2);
   END;
  / 
  
CREATE OR REPLACE PACKAGE body  WRK_INSERT_PKG AS  
PROCEDURE WRK_INSERT (EXT_TABLE_NAME IN VARCHAR2, WRK_TABLE_NAME IN VARCHAR2)AS
   BEGIN
    EXECUTE IMMEDIATE 'INSERT INTO '||WRK_TABLE_NAME||' SELECT * FROM '|| EXT_TABLE_NAME;
    
   END;
   END WRK_INSERT_PKG;
  / 